name: nodejs installer
on: workflow_dispatch
jobs:
  installation:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v3
     - name: install.js and npm
       run: |
         sudo apt-get update
         sudo apt-get install -y nodejs npm
     - name: check node js version
       run: |
         npm -v
         node -v
  verification:
    runs-on: ubuntu-latest
    needs: installation
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up node js
        uses: action/setup-node@v4
        with:
         node-version: '18'
      - name: install dependencies
        run: npm install
